import { WorkspaceSheet, Workspace, WorkspaceActions, WorkspaceCard, WorkspaceMenuSelect, WorkspaceProfileHeading, WorkspaceSurface, WorkspaceTabs, WorkspaceScroll } from '@/ui/Workspace'
import { LibraryTabs } from '@/ui/LibraryTabs'
import { LibraryBookCard, WatermarkAddCard } from '@/ui/LibraryCards'
import { DataControls } from '@/ui/DataControls'
import { useRef, useState, type ReactNode } from 'react'
import { Navigate, useLocation, useNavigate, useParams } from 'react-router'
import { useTranslation } from 'react-i18next'
import { CopyIcon, FolderInputIcon, InfoIcon, MapPinIcon, PencilIcon, PlusIcon, SaveIcon, Trash2Icon } from 'lucide-react'
import type { WorldLibraryService } from '@/core/application/world-library'
import { locationAncestors, type WorldLibrary, type LibraryGroup, type AlbumPhoto, type LocationSetting, type LocationCondition, type SettingImage } from '@/core/domain/world-library'
import type { CharacterCollection } from '@/core/domain/character-collection'
import { Button } from '@/ui/components/ui/button'
import { Sheet } from '@/ui/components/ui/sheet'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/ui/components/ui/alert-dialog'
import { DropdownMenuItem, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator } from '@/ui/components/ui/dropdown-menu'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/ui/components/ui/tooltip'
import { WorldPicture } from '@/ui/WorldPicture'

type Editing = { kind: 'album' | 'photo' | 'location' | 'condition'; value: LibraryGroup | AlbumPhoto | LocationSetting | LocationCondition; revision: number; isNew: boolean; copyOf?: string }
export function WorldLibraryPage({ service, library, collections, actions }: { service: WorldLibraryService; library: WorldLibrary; collections: CharacterCollection[]; actions: ReactNode }) {
  const { t } = useTranslation(), text = (key: string) => t(`world.${key}`)
  const { collectionId, locationId, conditionId, albumId, photoId } = useParams(), navigate = useNavigate(), pathname = useLocation().pathname
  const place = library.locations.find((l) => l.id === locationId), album = library.albums.find((a) => a.id === albumId), photo = library.photos.find((p) => p.id === photoId && p.albumId === albumId)
  const [editing, setEditing] = useState<Editing>(), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const [tag, setTag] = useState('')
  const [deleteOpen, setDeleteOpen] = useState(false)
  const [conditionDeleteOpen, setConditionDeleteOpen] = useState(false)
  const [photoDeleteOpen, setPhotoDeleteOpen] = useState(false)
  const [movePhotoOpen, setMovePhotoOpen] = useState(false)
  const [photoInfoOpen, setPhotoInfoOpen] = useState(false)
  const [settingUpload, setSettingUpload] = useState<{ conditionId?: string }>()
  const uploadInput = useRef<HTMLInputElement>(null)
  const [reference, setReference] = useState<{ snapshot: WorldLibrary; locationId: string; conditionId: string; photoId: string }>()
  const run = async (task: () => Promise<void>) => { setBusy(true); setError(''); try { await task() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  const begin = (kind: Editing['kind'], value?: Editing['value'], copy = false) => {
    const group = { id: crypto.randomUUID(), name: '', description: '', updatedAt: 0 }
    const copied = value && copy ? { ...value, id: crypto.randomUUID(), name: t('modelSheet.appearances.copyName', { name: value.name }) } : value
    setError(''); setEditing({ kind, revision: library.revision, isNew: !value || copy, copyOf: copy ? value?.id : undefined, value: copied ?? (kind === 'location' ? { ...group, collectionId: collectionId!, parentId: locationId ?? null, tags: [], consistency: '', images: [], conditions: [] } : kind === 'condition' ? { ...group, images: [] } : group) })
  }
  const save = (data: FormData) => run(async () => {
    if (!editing) return
    const { kind, value, revision, isNew, copyOf } = editing, fields = { id: value.id, name: String(data.get('name')).trim(), description: String(data.get('description') ?? '') }
    const command = kind === 'album' ? { resource: 'album' as const, action: isNew ? 'create' as const : 'update' as const, ...fields }
      : kind === 'photo' ? { resource: 'photo' as const, action: 'update' as const, ...fields, source: String(data.get('source')) }
      : kind === 'location' ? { resource: 'location' as const, action: isNew ? 'create' as const : 'update' as const, ...fields, collectionId: String(data.get('collectionId')), parentId: String(data.get('parentId') ?? '') || null, consistency: String(data.get('consistency')), tags: String(data.get('tags')).split(/[,，]/).map((item) => item.trim()).filter(Boolean) }
      : { resource: 'condition' as const, action: copyOf ? 'duplicate' as const : isNew ? 'create' as const : 'update' as const, locationId: locationId!, ...fields, ...(copyOf ? { id: copyOf } : {}) }
    const result = await service.update(command, revision); setEditing(undefined)
    if (kind === 'album') navigate(`/albums/${result.id}`)
    if (kind === 'location') navigate(`/collections/${data.get('collectionId')}/locations/${result.id}`)
    if (kind === 'photo') navigate(`/albums/${(value as AlbumPhoto).albumId}/photos/${result.id}`)
    if (kind === 'condition') navigate(`/collections/${collectionId}/locations/${locationId}/conditions/${result.id}`)
  })
  const remove = () => run(async () => {
    if (!editing) return
    const { kind, value, revision } = editing
    const command = kind === 'condition' ? { resource: 'condition' as const, action: 'delete' as const, locationId: locationId!, id: value.id }
      : { resource: kind as 'album' | 'photo' | 'location', action: 'delete' as const, id: value.id }
    await service.update(command, revision); setEditing(undefined)
    if (kind === 'album') navigate('/albums')
    if (kind === 'photo') navigate(`/albums/${albumId}`)
    if (kind === 'location') navigate(`/collections/${collectionId}/locations${(value as LocationSetting).parentId ? `/${(value as LocationSetting).parentId}` : ''}`)
  })
  const upload = <input ref={uploadInput} className="sr-only" type="file" multiple accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={(e) => { const files = Array.from(e.target.files ?? []); e.target.value = ''; if (files.length) void run(async () => { await service.upload(library, albumId ?? 'default', files) }) }} />
  const groupName = (id: string) => id === 'default' ? text('defaultCollection') : collections.find((c) => c.id === id)?.name ?? id
  const albumName = (a: LibraryGroup) => a.id === 'default' ? text('defaultAlbum') : a.name
  const settingImages = (images: SettingImage[], targetConditionId = '') => <section className="world-grid">
    {images.map((image) => <WorkspaceCard key={image.id} className="world-card" aspect="4 / 3" label={image.label}
      meta={<>{text(image.purpose)}<br />{image.source}</>}
      action={<Button variant="ghost" size="sm" className="world-card-remove" disabled={busy} onClick={() => void run(async () => { await service.update({ resource: 'reference', action: 'delete', locationId: locationId!, conditionId: targetConditionId || undefined, id: image.id }, library.revision) })}>{text('remove')}</Button>}>
      <WorldPicture service={service} hash={image.image.sha256} alt={image.label} />
    </WorkspaceCard>)}
    <WatermarkAddCard className="world-card" icon="collections" aspect="4 / 3" label={text('addSettingImage')} onClick={() => setSettingUpload({ conditionId: targetConditionId || undefined })} />
    <WatermarkAddCard className="world-card" icon="albums" aspect="4 / 3" label={text('addReference')} onClick={() => setReference({ snapshot: library, locationId: locationId ?? '', conditionId: targetConditionId, photoId: '' })} />
  </section>
  if ((albumId && !album) || (photoId && !photo) || (locationId && (!place || place.collectionId !== collectionId)) || (collectionId && !collections.some((c) => c.id === collectionId))) return <Workspace className="world-workspace"><p role="alert">404</p></Workspace>
  const locations = library.locations.filter((l) => l.collectionId === collectionId && (tag ? l.tags.includes(tag) : l.parentId === (locationId ?? null)))
  const locationView = pathname.includes('/conditions') ? 'conditions' : pathname.endsWith('/profile') ? 'profile' : 'images'
  const condition = place?.conditions.find((item) => item.id === conditionId)
  if (conditionId && !condition) return <Navigate to={`/collections/${collectionId}/locations/${locationId}/conditions`} replace />
  const locationActions = place && <WorkspaceActions aria-label={place.name}><TooltipProvider>
    <Tooltip><TooltipTrigger asChild><Button size="icon" variant="outline" aria-label={text('edit')} disabled={busy} onClick={() => begin('location', place)}><PencilIcon /></Button></TooltipTrigger><TooltipContent>{text('edit')}</TooltipContent></Tooltip>
    <Tooltip><TooltipTrigger asChild><Button size="icon" variant="outline" aria-label={text('duplicate')} disabled={busy} onClick={() => void run(async () => { const result = await service.update({ resource: 'location', action: 'duplicate', id: place.id }, library.revision); navigate(`/collections/${collectionId}/locations/${result.id}`) })}><CopyIcon /></Button></TooltipTrigger><TooltipContent>{text('duplicate')}</TooltipContent></Tooltip>
    <Tooltip><TooltipTrigger asChild><Button size="icon" variant="outline" aria-label={text('remove')} disabled={busy} onClick={() => setDeleteOpen(true)}><Trash2Icon /></Button></TooltipTrigger><TooltipContent>{text('remove')}</TooltipContent></Tooltip>
  </TooltipProvider></WorkspaceActions>
  const photoActions = photo && <WorkspaceActions aria-label={photo.name}><TooltipProvider>
    <Tooltip><TooltipTrigger asChild><Button size="icon" variant="outline" aria-label={text('generationDetails')} onClick={() => setPhotoInfoOpen(true)}><InfoIcon /></Button></TooltipTrigger><TooltipContent>{text('generationDetails')}</TooltipContent></Tooltip>
    <Tooltip><TooltipTrigger asChild><Button size="icon" variant="outline" aria-label={text('edit')} disabled={busy} onClick={() => begin('photo', photo)}><PencilIcon /></Button></TooltipTrigger><TooltipContent>{text('edit')}</TooltipContent></Tooltip>
    <Tooltip><TooltipTrigger asChild><Button size="icon" variant="outline" aria-label={text('moveToAlbum')} disabled={busy} onClick={() => setMovePhotoOpen(true)}><FolderInputIcon /></Button></TooltipTrigger><TooltipContent>{text('moveToAlbum')}</TooltipContent></Tooltip>
    <DataControls exportData={() => service.image(photo.image.sha256)} exportFilename={photo.image.filename} exportIconOnly exportLabel={text('download')} />
    <Tooltip><TooltipTrigger asChild><Button size="icon" variant="outline" aria-label={text('remove')} disabled={busy} onClick={() => setPhotoDeleteOpen(true)}><Trash2Icon /></Button></TooltipTrigger><TooltipContent>{text('remove')}</TooltipContent></Tooltip>
  </TooltipProvider></WorkspaceActions>
  const conditionPicker = place && <WorkspaceMenuSelect label={text('chooseCondition')} value={condition?.name ?? text('chooseCondition')} disabled={busy}>
    {condition && <><DropdownMenuItem onSelect={() => begin('condition', condition)}><PencilIcon />{text('rename')}</DropdownMenuItem>
      <DropdownMenuItem onSelect={() => begin('condition', condition, true)}><SaveIcon />{text('saveAs')}</DropdownMenuItem><DropdownMenuSeparator /></>}
    <DropdownMenuRadioGroup value={condition?.id} onValueChange={(id) => navigate(`/collections/${collectionId}/locations/${place.id}/conditions/${id}`)}>
      {place.conditions.map((item) => <DropdownMenuRadioItem key={item.id} value={item.id}>{item.name}</DropdownMenuRadioItem>)}
    </DropdownMenuRadioGroup>
    <DropdownMenuItem onSelect={() => begin('condition')}><PlusIcon />{text('createCondition')}</DropdownMenuItem>
    {condition && <><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onSelect={() => setConditionDeleteOpen(true)}><Trash2Icon />{text('remove')}</DropdownMenuItem></>}
  </WorkspaceMenuSelect>
  return <Workspace header={<>{place ? <WorkspaceTabs label={place.name} active={locationView}
      items={[{ id: 'images', label: text('images') }, { id: 'profile', label: text('locationProfile') }, { id: 'conditions', label: text('conditions') }]}
      onSelect={(id) => navigate(`/collections/${collectionId}/locations/${place.id}${id === 'images' ? '' : id === 'conditions' && place.conditions[0] ? `/conditions/${place.conditions[0].id}` : `/${id}`}`)}>{locationActions}</WorkspaceTabs>
    : collectionId && <WorkspaceTabs label={text('collection')} active="locations"
      items={[{ id: 'characters', label: text('characters') }, { id: 'locations', label: text('locations') }, { id: 'profile', label: t('books.profile') }]}
      onSelect={(id) => navigate(`/collections/${collectionId}${id === 'characters' ? '' : `/${id}`}`)}>{actions}</WorkspaceTabs>}
    {!collectionId && !album && !photo && <LibraryTabs active="albums" />}</>} className="world-workspace" data-workspace-view={place ? `location-${locationView}` : collectionId ? 'locations' : 'albums'} data-collection-id={collectionId} data-location-id={locationId} data-condition-id={conditionId} data-album-id={albumId} data-photo-id={photoId} data-has-uncommitted-input={Boolean(editing || movePhotoOpen || reference || settingUpload)}>
    {!collectionId && !album && !photo && <h1 className="sr-only">{text('albums')}</h1>}
<WorkspaceSurface surface={album ? 'paper' : undefined} className={`world-page${album ? ' album-page' : ''}${photo ? ' album-photo-page' : ''}`} aria-label={place?.name ?? photo?.name ?? (album ? albumName(album) : text(collectionId ? 'locations' : 'albums'))}><WorkspaceScroll>
    {error && <p role="alert" className="story-error">{error}</p>}{busy && <p role="status">{text('working')}</p>}
    {place && locationView === 'images' && <section className="world-section"><div className="world-heading"><h2>{text('images')}</h2></div>{settingImages(place.images)}</section>}
    {place && locationView === 'profile' && <div className="book-profile flex flex-col gap-4" aria-label={text('locationProfile')}>
      <WorkspaceProfileHeading label={text('locationProfile')} title={place.name} />
      <p className="whitespace-pre-wrap text-sm leading-7">{place.description || text('noDescription')}</p>
      <div className="world-tags">{place.tags.map((item) => <span key={item}>{item}</span>)}</div>
      <div><h3 className="font-heading text-lg font-semibold">{text('consistency')}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{place.consistency || text('noConsistency')}</p></div>
      <div><h3 className="font-heading text-lg font-semibold">{text('parent')}</h3><p className="mt-2 text-sm">{place.parentId ? locationAncestors(library, place.id).slice(0, -1).map(({ name }) => name).join(' / ') : text('root')}</p></div>
      <section className="world-section"><h2>{text('children')}</h2><div className="world-grid">{locations.map((item) => <WorkspaceCard className="world-card" key={item.id} to={`/collections/${collectionId}/locations/${item.id}`} aspect="4 / 3" label={<><MapPinIcon size={16} />{item.name}</>} meta={item.description}><WorldPicture service={service} hash={item.images.find((image) => image.purpose === 'design')?.image.sha256 ?? item.images[0]?.image.sha256} alt={item.name} /></WorkspaceCard>)}<WatermarkAddCard className="world-card" icon="collections" aspect="4 / 3" label={text('createLocation')} onClick={() => begin('location')} /></div></section>
    </div>}
    {place && locationView === 'conditions' && <><div className="mb-6 max-w-xl">{conditionPicker}</div>{condition ? <><p className="mb-6 max-w-[65ch] whitespace-pre-wrap text-sm leading-7">{condition.description || text('noDescription')}</p>{settingImages(condition.images, condition.id)}</> : <p>{text('empty')}</p>}</>}
    {collectionId && !place ? <section className="world-section"><div className="world-heading"><h2>{text('locations')}</h2><label>{text('filterTags')}<select value={tag} onChange={(e) => setTag(e.target.value)}><option value="">{text('all')}</option>{[...new Set(library.locations.filter((l) => l.collectionId === collectionId).flatMap((l) => l.tags))].map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="world-grid">{locations.map((item) => <WorkspaceCard className="world-card" key={item.id} to={`/collections/${collectionId}/locations/${item.id}`} aspect="4 / 3" label={<><MapPinIcon size={16} />{item.name}</>} meta={item.description}><WorldPicture service={service} hash={item.images.find((image) => image.purpose === 'design')?.image.sha256 ?? item.images[0]?.image.sha256} alt={item.name} /></WorkspaceCard>)}<WatermarkAddCard className="world-card" icon="collections" aspect="4 / 3" label={text('createLocation')} onClick={() => begin('location')} /></div></section> : !collectionId && photo ? <div className="album-photo-detail"><div className="flex justify-end">{photoActions}</div><div className="album-photo-print"><div className="album-photo-stage"><WorldPicture service={service} hash={photo.image.sha256} alt={photo.name} /><h2 className="album-photo-title">{photo.name}</h2></div>{photo.description && <p className="album-photo-description">{photo.description}</p>}</div></div> : !collectionId && album ? <><div className="world-heading album-heading"><div><h2>{albumName(album)}</h2>{album.description && <p>{album.description}</p>}</div><Button size="icon" variant="ghost" aria-label={text('edit')} onClick={() => begin('album', album)}><PencilIcon /></Button></div><div className="album-grid">{library.photos.filter((p) => p.albumId === album.id).map((p) => <WorkspaceCard className="album-photo" key={p.id} to={`/albums/${album.id}/photos/${p.id}`} aspect="4 / 3" label={p.name}><WorldPicture service={service} hash={p.image.sha256} alt={p.name} /></WorkspaceCard>)}<WatermarkAddCard className="album-photo album-add" icon="albums" aspect="4 / 3" label={text('addImages')} disabled={busy} onClick={() => uploadInput.current?.click()} />{upload}</div></> : !collectionId && <div className="bookshelf-grid">{library.albums.map((a) => <LibraryBookCard key={a.id} icon="albums" to={`/albums/${a.id}`} label={albumName(a)} />)}<WatermarkAddCard className="collection-cover" icon="albums" label={text('createAlbum')} onClick={() => begin('album')} /></div>}
    </WorkspaceScroll></WorkspaceSurface>
    <Sheet open={photoInfoOpen} onOpenChange={setPhotoInfoOpen}><WorkspaceSheet title={text('generationDetails')} surface="paper" aria-describedby={undefined} closeLabel={text('close')}>{photo && <div className="book-profile flex flex-col gap-4"><h2 className="text-xl">{photo.name}</h2>{photo.description && <p className="whitespace-pre-wrap leading-7">{photo.description}</p>}<div><h3 className="text-lg">{text('source')}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{photo.source || '—'}</p></div></div>}</WorkspaceSheet></Sheet>
    <Sheet open={Boolean(editing)} onOpenChange={(open) => { if (!open && !busy) setEditing(undefined) }}><WorkspaceSheet title={text('edit')}  aria-describedby={undefined} closeLabel={text('close')} onEscapeKeyDown={(e) => { if (busy) e.preventDefault() }} onPointerDownOutside={(e) => { if (busy) e.preventDefault() }}>{editing && <form key={editing.value.id} className="world-form" onSubmit={(e) => { e.preventDefault(); void save(new FormData(e.currentTarget)) }}><label>{text('name')}<input name="name" defaultValue={editing.value.name} maxLength={120} required disabled={busy} autoFocus /></label><label>{text('description')}<textarea name="description" defaultValue={editing.value.description} maxLength={8000} rows={4} disabled={busy} /></label>{editing.kind === 'location' && <><label>{text('collection')}<select name="collectionId" value={(editing.value as LocationSetting).collectionId} onChange={(e) => setEditing({ ...editing, value: { ...editing.value as LocationSetting, collectionId: e.target.value, parentId: null } })} disabled={busy}>{collections.map((c) => <option key={c.id} value={c.id}>{groupName(c.id)}</option>)}</select></label><label>{text('parent')}<select name="parentId" value={(editing.value as LocationSetting).parentId ?? ''} onChange={(e) => setEditing({ ...editing, value: { ...editing.value as LocationSetting, parentId: e.target.value || null } })} disabled={busy}><option value="">{text('root')}</option>{library.locations.filter((l) => l.collectionId === (editing.value as LocationSetting).collectionId && !locationAncestors(library, l.id).some((a) => a.id === editing.value.id)).map((l) => <option key={l.id} value={l.id}>{groupName(l.collectionId)} / {locationAncestors(library, l.id).map((a) => a.name).join(' / ')}</option>)}</select></label><label>{text('tags')}<input name="tags" defaultValue={(editing.value as LocationSetting).tags.join(', ')} maxLength={1200} disabled={busy} /></label><label>{text('consistency')}<textarea name="consistency" defaultValue={(editing.value as LocationSetting).consistency} maxLength={8000} rows={6} disabled={busy} /></label></>}{editing.kind === 'photo' && <label>{text('source')}<textarea name="source" defaultValue={(editing.value as AlbumPhoto).source} maxLength={2000} disabled={busy} /></label>}<Button disabled={busy}>{text('save')}</Button>{error && <p role="alert" className="story-error">{error}</p>}<Button type="button" variant="ghost" disabled={busy} onClick={() => setEditing(undefined)}>{text('cancel')}</Button>{editing.kind !== 'photo' && editing.value.name && !(editing.kind === 'album' && editing.value.id === 'default') && <details><summary>{text('remove')}</summary><p>{text('removeHint')}</p><Button type="button" variant="destructive" disabled={busy} onClick={() => void remove()}>{text('remove')}</Button></details>}</form>}</WorkspaceSheet></Sheet>
    <Sheet open={movePhotoOpen} onOpenChange={(open) => { if (!open && !busy) setMovePhotoOpen(false) }}><WorkspaceSheet title={text('moveToAlbum')} aria-describedby={undefined} closeLabel={text('close')}>{photo && <form className="world-form" onSubmit={(event) => { event.preventDefault(); const targetAlbumId = String(new FormData(event.currentTarget).get('albumId')); if (targetAlbumId === photo.albumId) { setMovePhotoOpen(false); return } void run(async () => { await service.update({ resource: 'photo', action: 'move', id: photo.id, albumId: targetAlbumId }, library.revision); setMovePhotoOpen(false); navigate(`/albums/${targetAlbumId}/photos/${photo.id}`) }) }}><label>{text('album')}<select name="albumId" defaultValue={photo.albumId} disabled={busy}>{library.albums.map((item) => <option key={item.id} value={item.id}>{albumName(item)}</option>)}</select></label><Button disabled={busy}>{text('moveToAlbum')}</Button>{error && <p role="alert" className="story-error">{error}</p>}</form>}</WorkspaceSheet></Sheet>
    <Sheet open={Boolean(reference)} onOpenChange={(open) => { if (!open && !busy) setReference(undefined) }}><WorkspaceSheet title={text('addReference')}  aria-describedby={undefined} closeLabel={text('close')}>{reference && <form className="world-form" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); void run(async () => {
      await service.update({ resource: 'reference', action: 'create', locationId: String(data.get('locationId')), conditionId: reference.conditionId || undefined, photoId: String(data.get('photoId')), label: String(data.get('label')).trim(), purpose: data.get('purpose') as SettingImage['purpose'] }, reference.snapshot.revision); setReference(undefined)
    }) }}><label>{text('chooseLocation')}<select name="locationId" required defaultValue={reference.locationId}><option value="">—</option>{library.locations.map((l) => <option key={l.id} value={l.id}>{groupName(l.collectionId)} / {locationAncestors(library, l.id).map((a) => a.name).join(' / ')}</option>)}</select></label><label>{text('chooseImage')}<select name="photoId" required value={reference.photoId} onChange={(e) => setReference({ ...reference, photoId: e.target.value })}><option value="">—</option>{library.photos.map((p) => <option key={p.id} value={p.id}>{albumName(library.albums.find((a) => a.id === p.albumId)!)} / {p.name}</option>)}</select></label>{reference.photoId && <WorldPicture service={service} hash={library.photos.find((p) => p.id === reference.photoId)?.image.sha256} alt={text('chooseImage')} />}<label>{text('label')}<input name="label" required maxLength={120} /></label><label>{text('images')}<select name="purpose"><option value="inspiration">{text('inspiration')}</option><option value="design">{text('design')}</option></select></label><Button disabled={busy}>{text('save')}</Button>{error && <p role="alert" className="story-error">{error}</p>}</form>}</WorkspaceSheet></Sheet>
    <Sheet open={Boolean(settingUpload)} onOpenChange={(open) => { if (!open && !busy) setSettingUpload(undefined) }}><WorkspaceSheet title={text('addSettingImage')} aria-describedby={undefined} closeLabel={text('close')}>{settingUpload && <form className="world-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget), file = data.get('file'); if (!(file instanceof File) || !file.size) return; void run(async () => { await service.uploadSetting(library, locationId!, file, String(data.get('label')).trim(), data.get('purpose') as SettingImage['purpose'], settingUpload.conditionId, String(data.get('source') ?? '')); setSettingUpload(undefined) }) }}>
      <label>{text('chooseImage')}<input name="file" type="file" accept="image/png,image/jpeg,image/webp" required disabled={busy} /></label>
      <label>{text('label')}<input name="label" required maxLength={120} disabled={busy} /></label>
      <label>{text('images')}<select name="purpose" disabled={busy}><option value="design">{text('design')}</option><option value="inspiration">{text('inspiration')}</option></select></label>
      <label>{text('source')}<textarea name="source" maxLength={2000} rows={3} disabled={busy} /></label>
      <Button disabled={busy}>{text('save')}</Button>{error && <p role="alert" className="story-error">{error}</p>}
    </form>}</WorkspaceSheet></Sheet>
    <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{text('remove')} {place?.name}?</AlertDialogTitle><AlertDialogDescription>{text('removeHint')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{text('cancel')}</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={busy} onClick={() => place && void run(async () => { await service.update({ resource: 'location', action: 'delete', id: place.id }, library.revision); navigate(`/collections/${collectionId}/locations${place.parentId ? `/${place.parentId}` : ''}`) })}>{text('remove')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={photoDeleteOpen} onOpenChange={setPhotoDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{text('remove')} {photo?.name}?</AlertDialogTitle><AlertDialogDescription>{text('removePhotoHint')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{text('cancel')}</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={busy} onClick={() => photo && void run(async () => { await service.update({ resource: 'photo', action: 'delete', id: photo.id }, library.revision); navigate(`/albums/${photo.albumId}`) })}>{text('remove')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={conditionDeleteOpen} onOpenChange={setConditionDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{text('remove')} {condition?.name}?</AlertDialogTitle><AlertDialogDescription>{text('removeHint')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{text('cancel')}</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={busy} onClick={() => condition && void run(async () => { await service.update({ resource: 'condition', action: 'delete', locationId: locationId!, id: condition.id }, library.revision); navigate(`/collections/${collectionId}/locations/${locationId}/conditions`) })}>{text('remove')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </Workspace>
}
